# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: Coverity Check

on:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '.gitignore'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  test:
    uses: schmidtw/workflow-test/.github/workflows/meson-coverity.yml@main
    with:
      repo: $GITHUB_REPOSITORY
      sha: $GITHUB_SHA
    secrets:
      coverity_key: invalid #${{ secrets.COVERITY_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
