# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '.gitignore'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  test:
    uses: schmidtw/workflow-test/.github/workflows/meson-unit-test.yml@main
    secrets:
      sonar_login: "invalid"
      github_token: ${{ secrets.GITHUB_TOKEN }}
