# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    tags:
      # Push events to matching v#.#.#*, ex: v1.2.3, v.2.4.6-beta
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    uses: schmidtw/workflow-test/.github/workflows/meson-release.yml@main
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
