# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    paths:
      - "CHANGELOG.md" # only try to tag if the CHANGELOG has been updated.
      - "meson.build"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel

    - name: Install Meson
      run: |
        pip3 install --user 'meson>=0.59.0'


    - uses: xmidt-org/release-builder-action@v2
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}

#
#    uses: schmidtw/workflow-test/.github/workflows/meson-release.yml@main
#    with:
#      github_repository: ${{ github.repository }}
#      github_workspace: ${{ github.workspace }}
#      provides: cutils
#    secrets:
#      github_token: ${{ secrets.GITHUB_TOKEN }}
