# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    paths:
      - "CHANGELOG.md" # only try to tag if the CHANGELOG has been updated.
    branches:
      - main

jobs:
  release:
    uses: schmidtw/workflow-test/.github/workflows/meson-release.yml@main
    with:
      github_repository: ${{ github.repository }}
      github_workspace: ${{ github.workspace }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
