# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    paths:
      - "CHANGELOG.md" # only try to tag if the CHANGELOG has been updated.
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create Release Bundle
      id: bundle
      uses: xmidt-org/release-builder-action@v2
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        meson-provides: cutils

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ steps.bundle.outputs.release-name }}
        tag: ${{ steps.bundle.outputs.release-tag }}
        draft: false
        prerelease: false
        body: ${{ steps.bundle.outputs.release-body }}
        artifacts: "${{ steps.bundle.outputs.artifact-dir }}/*"
        token: ${{ secrets.GITHUB_TOKEN }}
#
#    uses: schmidtw/workflow-test/.github/workflows/meson-release.yml@main
#    with:
#      github_repository: ${{ github.repository }}
#      github_workspace: ${{ github.workspace }}
#      provides: cutils
#    secrets:
#      github_token: ${{ secrets.GITHUB_TOKEN }}
